# Site settings
title: True bocal FAQ
email: nekresh@gmail.com
description: "Regrouper a un seul endroit les problemes ainsi que les resolutions du dump Bocal"
baseurl: "/bocal-faq"

# Build settings
markdown: kramdown
permalink: pretty
